main:
  - identifier: 'home'
    name: 'Home'
    pageref: '/'
    weight: 1
  - identifier: 'posts'
    name: 'Posts'
    pageref: '/posts'
    weight: 2
  - identifier: 'tags'
    name: 'Tags'
    pageref: '/tags'
    weight: 2